param ($configuration = "Release", $frameworkVersion = "net10.0")

# Old package (MMXMLDoc2Markdown) and the renamed one both provide the 'mmxmldoc2md' command;
# remove the old one first so the install doesn't conflict on a reused build agent.
dotnet tool uninstall --global MMXMLDoc2Markdown 2>$null
dotnet tool update --global Meshmakers.XMLDoc2Markdown

$modulePath = Split-Path -Parent $MyInvocation.MyCommand.Definition
$baseBinPath = Join-Path $modulePath "../src"
$baseOutputPath = Join-Path $modulePath "../bin/$configuration/documentation"

# Clean directory
if (Test-Path -Path $baseOutputPath) {
    Write-Host "Remove existing documentation at '$baseOutputPath'"
    Remove-Item -Path $baseOutputPath -Recurse -Force
}

# Documents the assemblies this repo actually builds. Communication.Contracts,
# Sdk.Common, and Sdk.ServiceClient stayed in octo-sdk during the Phase 3 cut;
# their docs are generated by octo-sdk/scripts/createDocumentation.ps1.

$outputPath = "$baseOutputPath/apiReference/Sdk.Pipeline"
$sourcePath = "$baseBinPath/Sdk.Pipeline/bin/$configuration/$frameworkVersion/Meshmakers.Octo.Sdk.Pipeline.dll"
Write-Host "Creating documentation for $sourcePath, doc is generated at $outputPath"
mmxmldoc2md $sourcePath $outputPath

$outputPath = "$baseOutputPath/apiReference/Sdk.Adapters"
$sourcePath = "$baseBinPath/Sdk.Adapters/bin/$configuration/$frameworkVersion/Meshmakers.Octo.Sdk.Adapters.dll"
Write-Host "Creating documentation for $sourcePath, doc is generated at $outputPath"
mmxmldoc2md $sourcePath $outputPath

$outputPath = "$baseOutputPath/apiReference/Sdk.Common.Web"
$sourcePath = "$baseBinPath/Sdk.Common.Web/bin/$configuration/$frameworkVersion/Meshmakers.Octo.Sdk.Common.Web.dll"
Write-Host "Creating documentation for $sourcePath, doc is generated at $outputPath"
mmxmldoc2md $sourcePath $outputPath

$outputPath = "$baseOutputPath/apiReference/Sdk.SimulationNodes"
$sourcePath = "$baseBinPath/Sdk.SimulationNodes/bin/$configuration/$frameworkVersion/Meshmakers.Octo.Sdk.SimulationNodes.dll"
Write-Host "Creating documentation for $sourcePath, doc is generated at $outputPath"
mmxmldoc2md $sourcePath $outputPath
